AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

  EnableVersioning:
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
    Description: Enable or disable versioning for the bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref EnableVersioning